### ISSUE TITLE
[Bug] Two operators with the same shortcut but different execution modes cause both to fail

### ISSUE THREAD

**Issue by MichaelColina** [Pluglug/pie-menu-editor-fork#12]
## Bug Overview:

- Blender Version: 4.3.0
- PME Version: 1.8.7
- OS: windows 10 

## Description
[my_pie_menus-2.json](https://github.com/user-attachments/files/18112108/my_pie_menus-2.json)

i tried setting up “middle mouse” with “press” mode on the “Mesh” pie menu while other shortcut as well uses “middle mouse” with “click” mode inside the operator and an additional “drag” toggle on but from the addon’s preferences from “context pie” addon from extensions then pressing the middle mouse shortcut throws an error that doesnt allow the other command to work either but disabling that pie menu allows using the context menu operator to work again… 

Although i solve it by just using a different shortcut combination. one Context pie menu operator now set to middle mouse click mode instead of click mode + drag toggle, and the PME shortcut with shift-middle mouse press mode, then added another shortcut with middle mouse click+drag mode for the blender context menu...

Info tab error:
```
Python: Traceback (most recent call last):
File “C:\Users\Usuario\AppData\Roaming\Blender Foundation\Blender\4.3\scripts\addons\pie_menu_editor\operators.py”, line 2081, in invoke
if not apm.executed:
^^^^^^^^^^^^
File “C:\Program Files\Blender Foundation\Blender 4.3\4.3\scripts\modules\bpy_types.py”, line 936, in getattribute
properties = _StructRNA.path_resolve(self, “properties”)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: StructRNA of type WM_OT_pme_user_pie_menu_call has been removed
```

**Comment by oRazeD** [comment]
Hey @MichaelColina, could you attempt recreating the bug using the following build? You may get the same result, in which case we will investigate directly, but I'd like to try my luck here. You may need to uninstall before/after you install the new build to avoid overlapping add-ons.

Here's the build link:
https://github.com/Pluglug/pie-menu-editor-fork/archive/refs/heads/4.3-compat.zip

Thanks for assisting with this process! It's much appreciated.

**Comment by MichaelColina** [comment]
Sorry for late reply... Ok i tried again in that build and the bug doesn't appear this time but probably the other addon was overriding something in this one, since the drag option with middle mouse and press mode in that context pie addon "locks" the pie menu with a delay and also the shortcut meaning that it doesn't allow other shortcut function (like click or press mode with middle mouse) to execute. i am closing this for now.
