### ISSUE TITLE
[Bug] blf.size() DPI argument removal causes Overlay issue

### ISSUE THREAD

**Issue by Pluglug** [Pluglug/pie-menu-editor-fork#2]
## Bug Overview
- **Summary**: In Blender 4.0.0 beta, the `blf.size()` function no longer supports the `dpi` argument, causing an error in PME's `overlay.py` file. As a result, the overlay does not display correctly when using the Modal Operator.

## Steps to Reproduce
1. Launch PME (v1.18.7) in Blender 4.0.0 beta.
2. Create a new PME Modal Operator and assign a preferred hotkey.
3. Press the hotkey in the 3D Viewport to invoke the Modal Operator.
4. The console shows the error: `TypeError: blf.size() takes exactly 2 arguments (3 given)` and the overlay functionality does not work.

## Expected Behavior
- The text "Modal Operator" should appear in the 3D Viewport.

## Environment
- **Blender Version**: 4.0.0 beta
- **PME Version**: 1.18.7
- **OS**: Windows10

## Supporting Materials
- Console log example: `TypeError: blf.size() takes exactly 2 arguments (3 given)`
- Fix: Update `blf.size(0, size, 72)` to `blf.size(0, size)` in `overlay.py` at lines 98, 177, and 183.

## Additional Information
- Removing the `dpi` argument defaults to the value `dpi=72`, maintaining backward compatibility.
- Further reports will be provided after testing the fix.

**Comment by Pluglug** [comment]
This is a reassertion of a known issue previously discussed. For details, please refer to the original report:  [Original Report: blf.size() DPI argument removal issue](https://blenderartists.org/t/pie-menu-editor-1-18-7/662456/4862?u=pluglug)

**Comment by oRazeD** [comment]
I believe removing the extra argument is a perfect resolution to this issue.

As mentioned in the original description, the value used in PME is the same as having no argument provided, so it is automatically backwards compatible. I submitted this change in 4c8b6fbc87fe3a51ea050e5cb483cdbbb930334b, feel free to close the issue if you have no other comments!
